version: "3.9"

services:
  voitity-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voitity-admin-app
    working_dir: /app/src
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID:-167788873467-qnbp52ma1n1a3b12je3iu09e80gss8o2.apps.googleusercontent.com}
    volumes:
      - ./src:/app/src
      - /app/src/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 3000
